/**
 * @license
 * Copyright 2026 a7mddra
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Context Windowing Engine
 *
 * Replaces the naive `slice(-6)` with a tiered memory architecture:
 *   Tier 0: Immortal Anchors (image_brief, image_description, user_first_msg) — always in frame.md
 *   Tier 1: Rolling Summary — compressed older turns (generated by cheap model)
 *   Tier 2: Verbatim Window — last N turns kept in full
 *
 * Inspired by OpenAI Codex's compaction architecture but adapted for chat UX.
 */

import { brainSessionStore } from "./store";
import { normalizeMessageForHistory } from "./attachments/memory";
import {
  compressConversationHistory,
  persistConversationSummary,
} from "../provider";

/** How many messages (user+assistant pairs) to keep verbatim. */
const VERBATIM_WINDOW_SIZE = 6;

/** Minimum messages before triggering summarization (must exceed verbatim window). */
const SUMMARIZATION_THRESHOLD = VERBATIM_WINDOW_SIZE + 2; // 8 messages

/** Approximate bytes per token (same as Codex: APPROX_BYTES_PER_TOKEN = 4). */
const BYTES_PER_TOKEN = 4;

/** Estimate token count using byte-length heuristic. */
export function approxTokenCount(text: string): number {
  return Math.ceil(new TextEncoder().encode(text).length / BYTES_PER_TOKEN);
}

/**
 * Build the context window for the current turn.
 *
 * Returns:
 * - `historyLog`: formatted verbatim recent turns (last VERBATIM_WINDOW_SIZE)
 * - `rollingSummary`: the compressed summary of older turns (or empty)
 *
 * This replaces the old `formatHistoryLog()` which just dumped everything.
 */
export function buildContextWindow(): {
  historyLog: string;
  rollingSummary: string;
} {
  const history = brainSessionStore.conversationHistory;

  // Format verbatim window (last N messages)
  const verbatimStart = Math.max(0, history.length - VERBATIM_WINDOW_SIZE);
  const verbatimMessages = history.slice(verbatimStart);

  const historyLog =
    verbatimMessages.length === 0
      ? "(No previous messages)"
      : verbatimMessages
          .map(
            ({ role, content }) =>
              `**${role}**: ${normalizeMessageForHistory(content)}`,
          )
          .join("\n\n");

  const rollingSummary = brainSessionStore.conversationSummary || "";

  return { historyLog, rollingSummary };
}

/**
 * Check if summarization should be triggered, and if so, fire it async.
 *
 * Called after each assistant response is added to history.
 * Summarization is fire-and-forget — the user never waits.
 *
 * @param chatId - Active chat ID for persisting the summary
 */
export function maybeCompressHistory(chatId: string | null): void {
  const history = brainSessionStore.conversationHistory;

  // Don't compress if below threshold
  if (history.length < SUMMARIZATION_THRESHOLD) {
    return;
  }

  // Don't compress if no API key
  if (!brainSessionStore.storedApiKey) {
    return;
  }

  // Calculate what needs compressing: everything except the verbatim window
  const compressEnd = history.length - VERBATIM_WINDOW_SIZE;
  if (compressEnd <= 0) {
    return;
  }

  const toCompress = history.slice(0, compressEnd);
  const imageBrief = brainSessionStore.imageBrief || "";

  // Format the turns to compress
  const historyText = toCompress
    .map(
      ({ role, content }) =>
        `**${role}**: ${normalizeMessageForHistory(content)}`,
    )
    .join("\n\n");

  console.log(
    `[Summarizer] Compressing ${toCompress.length} older messages (${approxTokenCount(historyText)} est. tokens)`,
  );

  // Fire and forget — async, non-blocking
  compressConversationHistory(
    brainSessionStore.storedApiKey,
    imageBrief,
    historyText,
  )
    .then((summary) => {
      if (summary) {
        // Merge with existing summary if present
        const existingSummary = brainSessionStore.conversationSummary;
        if (existingSummary) {
          brainSessionStore.conversationSummary = `${existingSummary}\n\n---\n\n${summary}`;
        } else {
          brainSessionStore.conversationSummary = summary;
        }

        console.log(
          `[Summarizer] Summary updated (${brainSessionStore.conversationSummary.length} chars)`,
        );

        // Trim history: keep only the verbatim window now that older turns are compressed
        brainSessionStore.conversationHistory = history.slice(compressEnd);

        console.log(
          `[Summarizer] History trimmed to ${brainSessionStore.conversationHistory.length} messages`,
        );

        // Persist summary to disk
        if (chatId) {
          persistConversationSummary(
            chatId,
            brainSessionStore.conversationSummary,
          ).catch((e) => {
            console.warn("[Summarizer] Failed to persist summary:", e);
          });
        }
      }
    })
    .catch((e) => {
      // Graceful degradation: if summarization fails, do nothing.
      // The old history stays, just slightly over the ideal window.
      console.warn("[Summarizer] Compression failed (non-fatal):", e);
    });
}

/**
 * Set the conversation summary directly (used when restoring from saved chat).
 */
export function setConversationSummary(summary: string | null): void {
  brainSessionStore.conversationSummary = summary;
}

/**
 * Get the current conversation summary.
 */
export function getConversationSummary(): string | null {
  return brainSessionStore.conversationSummary;
}
