# -----------------------------------------------------------------------------
# RUNTIME IMAGE (Used by SMOKETEST)
# -----------------------------------------------------------------------------
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libxkbcommon-x11-0 \
    libxcb-cursor0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-shape0 \
    libxcb-shm0 \
    libxcb-sync1 \
    libxcb-xfixes0 \
    libxcb-xinerama0 \
    libfontconfig1 \
    libdbus-1-3 \
    && rm -rf /var/lib/apt/lists/*

COPY dist /app

WORKDIR /app

ENV QT_QPA_PLATFORM=xcb
ENV LD_LIBRARY_PATH=/app/libs
ENV QT_PLUGIN_PATH=/app/plugins
ENV QT_QPA_PLATFORM_PLUGIN_PATH=/app/plugins/platforms
ENV QT_DEBUG_PLUGINS=1

CMD ["/app/capture"]