[workspace]
members = [
    "crates/*",
    "squigit-cli",
    "squigit-ocr",
    "squigit-rs",
    "xtask",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/squigit-org/squigit"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = "debuginfo"
panic = "abort"

[profile.dev.package.blake3]
opt-level = 3

[profile.dev.package.crc32fast]
opt-level = 3

[profile.dev.package.fast_image_resize]
opt-level = 3

[profile.dev.package.fdeflate]
opt-level = 3

[profile.dev.package.image]
opt-level = 3

[profile.dev.package.image-webp]
opt-level = 3

[profile.dev.package.libwebp-sys]
opt-level = 3

[profile.dev.package.miniz_oxide]
opt-level = 3

[profile.dev.package.moxcms]
opt-level = 3

[profile.dev.package.png]
opt-level = 3

[profile.dev.package.pxfm]
opt-level = 3

[profile.dev.package.simd-adler32]
opt-level = 3

[profile.dev.package.squigit-harness]
opt-level = 3

[profile.dev.package.zlib-rs]
opt-level = 3

[profile.dev.package.zune-inflate]
opt-level = 3

[profile.dev.package.zune-jpeg]
opt-level = 3

[profile.release.package.blake3]
opt-level = 3

[profile.release.package.crc32fast]
opt-level = 3

[profile.release.package.fast_image_resize]
opt-level = 3

[profile.release.package.fdeflate]
opt-level = 3

[profile.release.package.image]
opt-level = 3

[profile.release.package.image-webp]
opt-level = 3

[profile.release.package.libwebp-sys]
opt-level = 3

[profile.release.package.miniz_oxide]
opt-level = 3

[profile.release.package.moxcms]
opt-level = 3

[profile.release.package.png]
opt-level = 3

[profile.release.package.pxfm]
opt-level = 3

[profile.release.package.simd-adler32]
opt-level = 3

[profile.release.package.squigit-harness]
opt-level = 3

[profile.release.package.zlib-rs]
opt-level = 3

[profile.release.package.zune-inflate]
opt-level = 3

[profile.release.package.zune-jpeg]
opt-level = 3
