// Copyright 2026 a7mddra
// SPDX-License-Identifier: Apache-2.0

use std::path::PathBuf;

#[cfg(target_os = "windows")]
const SCRIPT_FILE_NAME: &str = "install-ocr.ps1";
#[cfg(not(target_os = "windows"))]
const SCRIPT_FILE_NAME: &str = "install-ocr.sh";

/// Unix installer: Homebrew on macOS, APT/DNF repository setup + install on
/// Linux (mirrors distribution/.github install docs). Idempotent: re-running
/// re-registers the repository and installs (or keeps) squigit-ocr.
#[cfg(not(target_os = "windows"))]
const INSTALL_OCR_SH: &str = r#"#!/bin/sh
# Auto-generated by Squigit. Installs the squigit-ocr engine.
# Safe to inspect before running: registers the Squigit OCR package
# repository, then installs the squigit-ocr package. Requires sudo on Linux.
set -eu

if [ "$(uname -s)" = "Darwin" ]; then
  brew install squigit-org/tap/squigit-ocr
  exit 0
fi

if command -v apt-get >/dev/null 2>&1; then
  sudo mkdir -p /etc/apt/keyrings
  curl -fsSL https://squigit-org.github.io/squigit-ocr/keys/squigit-ocr.asc \
    | gpg --dearmor \
    | sudo tee /etc/apt/keyrings/squigit-ocr.gpg >/dev/null
  echo "deb [signed-by=/etc/apt/keyrings/squigit-ocr.gpg] https://github.com/squigit-org/squigit-ocr/raw/main/apt stable ocr" \
    | sudo tee /etc/apt/sources.list.d/squigit-ocr.list >/dev/null
  sudo apt-get update
  sudo apt-get install -y squigit-ocr
elif command -v dnf >/dev/null 2>&1; then
  sudo curl -fsSL https://squigit-org.github.io/squigit-ocr/rpm/squigit-ocr.repo \
    -o /etc/yum.repos.d/squigit-ocr.repo
  sudo dnf install -y squigit-ocr
else
  echo "squigit-ocr install is not supported on this Linux distribution (needs apt or dnf)." >&2
  exit 1
fi
"#;

/// Windows installer: Winget package SquigitOrg.SquigitOCR.
#[cfg(target_os = "windows")]
const INSTALL_OCR_PS1: &str = "# Auto-generated by Squigit. Installs the squigit-ocr engine.\r\n# Safe to inspect before running: installs Squigit OCR from Winget.\r\n$ErrorActionPreference = \"Stop\"\r\nwinget install --id SquigitOrg.SquigitOCR --exact --source winget --scope user --silent --disable-interactivity --accept-source-agreements --accept-package-agreements\r\n";

/// Absolute path of the generated installer script (squigit config dir).
pub fn install_script_path() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("/tmp"))
        .join("squigit")
        .join(SCRIPT_FILE_NAME)
}

/// Materialise the installer script if missing and return its path.
pub fn ensure_install_script() -> Result<PathBuf, String> {
    let path = install_script_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| {
            format!(
                "Failed to create OCR installer directory {}: {error}",
                parent.display()
            )
        })?;
    }

    #[cfg(target_os = "windows")]
    let script = INSTALL_OCR_PS1;
    #[cfg(not(target_os = "windows"))]
    let script = INSTALL_OCR_SH;
    std::fs::write(&path, script).map_err(|error| {
        format!(
            "Failed to write OCR installer script {}: {error}",
            path.display()
        )
    })?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = std::fs::metadata(&path)
            .map_err(|error| format!("Failed to stat OCR installer script: {error}"))?
            .permissions();
        permissions.set_mode(0o700);
        std::fs::set_permissions(&path, permissions)
            .map_err(|error| format!("Failed to chmod OCR installer script: {error}"))?;
    }
    Ok(path)
}

/// Run the generated installer and wait for it to finish.
pub fn install_engine() -> Result<(), String> {
    let path = ensure_install_script()?;

    #[cfg(target_os = "windows")]
    let status = std::process::Command::new("powershell.exe")
        .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-File"])
        .arg(&path)
        .status();

    #[cfg(not(target_os = "windows"))]
    let status = std::process::Command::new(&path).status();

    let status = status
        .map_err(|error| format!("Failed to start OCR installer {}: {error}", path.display()))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "OCR installer {} exited with {status}",
            path.display()
        ))
    }
}
