/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeImage(
  imagePath: string,
  model: string,
  userMessage: string | undefined | null,
  onEvent: (err: null | Error, event: NapiStreamEvent) => void,
): Promise<NapiAnalyzeResult>;

export declare function appendThreadMessage(
  threadId: string,
  role: string,
  content: string,
): void;

export declare function cancelRequest(
  channelId?: string | undefined | null,
): Promise<void>;

export declare function clearActiveProfile(): void;

export declare function compressConversation(
  apiKey: string,
  imageBrief: string,
  historyToCompress: string,
  model: string,
): Promise<string>;

export declare function deleteThread(threadId: string): void;

export declare function deleteProfile(profileId: string): void;

export declare function findProfileByEmail(email: string): NapiProfile | null;

export declare function generateThreadTitle(
  apiKey: string,
  model: string,
  promptContext: string,
): Promise<string>;

export declare function generateImageBrief(
  apiKey: string,
  imagePath: string,
  model: string,
): Promise<string>;

export declare function getActiveProfileId(): string | null;

export declare function getApiKey(
  profileId: string,
  provider: string,
): string | null;

export declare function getImagePath(hash: string): string;

export declare function getReverseImageSearchUrl(
  threadId: string,
): string | null;

export declare function getProfile(profileId: string): NapiProfile | null;

export declare function getRollingSummary(threadId: string): string | null;

export declare function getStoreBaseDir(): string;

export declare function hasProfiles(): boolean;

export declare function listThreads(): Array<NapiThreadMetadata>;

export declare function listProfiles(): Array<NapiProfile>;

export declare function loadThread(threadId: string): NapiThreadData;

export interface NapiAnalyzeResult {
  threadId: string;
  title: string;
  assistantMessage: string;
  imagePath: string;
  imageBrief?: string;
}

export interface NapiAuthResult {
  id: string;
  name: string;
  email: string;
  avatar: string;
  originalPicture?: string;
}

export interface NapiThreadData {
  metadata: NapiThreadMetadata;
  messages: Array<NapiThreadMessage>;
  rollingSummary?: string;
  imageBrief?: string;
}

export interface NapiThreadMessage {
  role: string;
  content: string;
  timestamp: string;
}

export interface NapiThreadMetadata {
  id: string;
  title: string;
  imageHash: string;
  createdAt: string;
  updatedAt: string;
  isPinned: boolean;
  ocrLang?: string;
  imageTone?: string;
  reverseImageSearchUrl?: string;
}

export interface NapiProfile {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  originalAvatar?: string;
  createdAt: string;
  lastUsedAt: string;
}

export interface NapiPromptResult {
  threadId: string;
  assistantMessage: string;
  normalizedUserMessage: string;
}

export interface NapiStoredImage {
  hash: string;
  path: string;
  tone?: string;
}

/** Stream event sent via ThreadsafeFunction callback. */
export interface NapiStreamEvent {
  eventType: string;
  token?: string;
  message?: string;
  id?: string;
  name?: string;
  status?: string;
  args?: string;
  result?: string;
}

export declare function profileCount(): number;

export declare function promptThread(
  threadId: string,
  model: string,
  userMessage: string,
  onEvent: (err: null | Error, event: NapiStreamEvent) => void,
): Promise<NapiPromptResult>;

export declare function requestQuickAnswer(channelId: string): Promise<void>;

export declare function saveApiKey(
  profileId: string,
  provider: string,
  key: string,
): string;

export declare function saveReverseImageSearchUrl(
  threadId: string,
  url: string,
): void;

export declare function saveRollingSummary(
  threadId: string,
  summary: string,
): void;

export declare function setActiveProfile(profileId: string): void;

export declare function startGoogleAuth(): Promise<NapiAuthResult>;

export declare function storeImageFromPath(path: string): NapiStoredImage;

export declare function streamThread(
  apiKey: string,
  model: string,
  isInitialTurn: boolean,
  imagePath: string | undefined | null,
  imageDescription: string | undefined | null,
  userFirstMsg: string | undefined | null,
  historyLog: string | undefined | null,
  rollingSummary: string | undefined | null,
  userMessage: string,
  channelId: string,
  threadId: string | undefined | null,
  userName: string | undefined | null,
  userEmail: string | undefined | null,
  userInstruction: string | undefined | null,
  imageBrief: string | undefined | null,
  onEvent: (err: null | Error, event: NapiStreamEvent) => void,
): Promise<void>;

export declare function updateThreadMetadata(
  metadata: NapiThreadMetadata,
): void;

export declare function validateAuthCredentials(): void;
