/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare function append_thread_message(threadId: string, role: string, content: string): void

export declare function cancel_download_ocr_model(modelId: string): void

export declare function cancel_google_auth(): void

export declare function cancel_request(channelId?: string | undefined | null): Promise<void>

export declare function clear_active_profile(): void

export declare function copy_image_from_path_to_clipboard(path: string): void

export declare function copy_image_to_clipboard(imageBase64: string): void

export declare function create_thread(title: string, imageHash: string, ocrLang?: string | undefined | null): string

export declare function delete_profile(profileId: string): void

export declare function delete_thread(threadId: string): void

export declare function detect_image_tone(bytes: Buffer): string | null

export declare function download_ocr_model(modelId: string, url: string, progressCb: (progressJson: string) => void): Promise<string>

export declare function encrypt_and_save_api_key(profileId: string, provider: string, key: string): string

export declare function generate_image_brief(apiKey: string, imagePath: string, model: string): Promise<string>

export declare function generate_thread_title(apiKey: string, model: string, promptContext: string): Promise<string>

export declare function get_active_profile(): NapiProfile | null

export declare function get_active_profile_id(): string | null

export declare function get_api_key(profileId: string, provider: string): string | null

export declare function get_image_path(hash: string): string

export declare function get_linux_package_manager(): string

export declare function get_machine_info(): string

export declare function get_model_path(modelId: string): string

export declare function get_profile(profileId: string): NapiProfile | null

export declare function get_profile_snapshot(): NapiProfileSnapshot

export declare function get_reverse_image_search_url(threadId: string): string | null

export declare function get_store_base_dir(): string

export declare function get_system_theme(): string

export declare function has_profiles(): boolean

export declare function hydrate_avatar(url: string, profileId?: string | undefined | null): Promise<string>

export declare function list_downloaded_models(): Array<string>

export declare function list_profiles(): Array<NapiProfile>

export declare function list_threads(): string

export declare function load_thread(threadId: string): string

export interface NapiAuthResult {
  id: string
  name: string
  email: string
  avatarBase64?: string
  avatarUrl?: string
}

export interface NapiProfile {
  id: string
  name: string
  email: string
  avatarBase64?: string
  avatarUrl?: string
  createdAt: string
  lastUsedAt: string
}

export interface NapiProfileSnapshot {
  activeProfileId?: string
  activeProfile?: NapiProfile
  profiles: Array<NapiProfile>
}

export interface NapiStoredImage {
  hash: string
  path: string
  tone?: string
}

export interface NapiStreamEvent {
  eventType: string
  token?: string
  message?: string
  id?: string
  name?: string
  status?: string
  args?: string
  result?: string
}

export interface NapiSttEvent {
  eventType: string
  text?: string
  isFinal?: boolean
  status?: string
  message?: string
}

export interface NapiSttOptions {
  model?: string
  language?: string
}

export declare function ocr_image(imagePath: string, isBase64: boolean, modelName: string): Promise<string>

export declare function play_ui_sound(effect: string): void

export declare function process_image_path(path: string): NapiStoredImage

export declare function profile_count(): number

export declare function read_clipboard_image(): NapiStoredImage

export declare function read_clipboard_text(): string

export declare function request_quick_answer(channelId: string): Promise<void>

export declare function run_sidecar_version(command: string): Promise<string>

export declare function save_image_tone(threadId: string, tone: string): void

export declare function save_reverse_image_search_url(threadId: string, url: string): void

export declare function set_active_profile(profileId: string): void

export declare function start_google_auth(): Promise<NapiAuthResult>

export declare function start_stt(options: NapiSttOptions | undefined | null, onEvent: (err: null | Error, event: NapiSttEvent) => void): Promise<void>

export declare function stop_stt(): Promise<void>

export declare function store_file_from_path(path: string): NapiStoredImage

export declare function store_image_from_path(path: string): NapiStoredImage

export declare function stream_thread(apiKey: string, model: string, isInitialTurn: boolean, imagePath: string | undefined | null, imageDescription: string | undefined | null, userFirstMsg: string | undefined | null, historyLog: string | undefined | null, userMessage: string, channelId: string, threadId: string | undefined | null, userName: string | undefined | null, userEmail: string | undefined | null, imageBrief: string | undefined | null, onEvent: (err: null | Error, event: NapiStreamEvent) => void): Promise<void>

export declare function update_thread_metadata(metadataJson: string): void

export declare function upload_image_to_imgbb(imagePath: string, apiKey: string): Promise<string>
