/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeImage(imagePath: string, model: string, userMessage: string | undefined | null, onEvent: (err: null | Error, event: NapiStreamEvent) => void): Promise<NapiAnalyzeResult>

export declare function appendChatMessage(chatId: string, role: string, content: string): void

export declare function cancelGoogleAuth(): void

export declare function cancelRequest(channelId?: string | undefined | null): Promise<void>

export declare function clearActiveProfile(): void

export declare function compressConversation(apiKey: string, imageBrief: string, historyToCompress: string, model: string): Promise<string>

export declare function deleteChat(chatId: string): void

export declare function deleteProfile(profileId: string): void

export declare function findProfileByEmail(email: string): NapiProfile | null

export declare function generateChatTitle(apiKey: string, model: string, promptContext: string): Promise<string>

export declare function generateImageBrief(apiKey: string, imagePath: string, model: string): Promise<string>

export declare function getActiveProfileId(): string | null

export declare function getApiKey(profileId: string, provider: string): string | null

export declare function getImagePath(hash: string): string

export declare function getImgbbUrl(chatId: string): string | null

export declare function getProfile(profileId: string): NapiProfile | null

export declare function getRollingSummary(chatId: string): string | null

export declare function getStoreBaseDir(): string

export declare function hasProfiles(): boolean

export declare function listChats(): Array<NapiChatMetadata>

export declare function listProfiles(): Array<NapiProfile>

export declare function loadChat(chatId: string): NapiChatData

export interface NapiAnalyzeResult {
  chatId: string
  title: string
  assistantMessage: string
  imagePath: string
  imageBrief?: string
}

export interface NapiAuthResult {
  id: string
  name: string
  email: string
  avatar: string
  originalPicture?: string
}

export interface NapiChatData {
  metadata: NapiChatMetadata
  messages: Array<NapiChatMessage>
  rollingSummary?: string
  imageBrief?: string
  imgbbUrl?: string
}

export interface NapiChatMessage {
  role: string
  content: string
  timestamp: string
}

export interface NapiChatMetadata {
  id: string
  title: string
  imageHash: string
  createdAt: string
  updatedAt: string
  isPinned: boolean
  isStarred: boolean
  ocrLang?: string
  imageTone?: string
}

export interface NapiProfile {
  id: string
  name: string
  email: string
  avatar?: string
  originalAvatar?: string
  createdAt: string
  lastUsedAt: string
}

export interface NapiPromptResult {
  chatId: string
  assistantMessage: string
  normalizedUserMessage: string
}

export interface NapiStoredImage {
  hash: string
  path: string
  tone?: string
}

/** Stream event sent via ThreadsafeFunction callback. */
export interface NapiStreamEvent {
  eventType: string
  token?: string
  message?: string
  id?: string
  name?: string
  status?: string
  args?: string
  result?: string
}

export declare function profileCount(): number

export declare function promptChat(chatId: string, model: string, userMessage: string, onEvent: (err: null | Error, event: NapiStreamEvent) => void): Promise<NapiPromptResult>

export declare function requestQuickAnswer(channelId: string): Promise<void>

export declare function saveApiKey(profileId: string, provider: string, key: string): string

export declare function saveImgbbUrl(chatId: string, url: string): void

export declare function saveRollingSummary(chatId: string, summary: string): void

export declare function setActiveProfile(profileId: string): void

export declare function startGoogleAuth(): Promise<NapiAuthResult>

export declare function storeImageFromPath(path: string): NapiStoredImage

export declare function streamChat(apiKey: string, model: string, isInitialTurn: boolean, imagePath: string | undefined | null, imageDescription: string | undefined | null, userFirstMsg: string | undefined | null, historyLog: string | undefined | null, rollingSummary: string | undefined | null, userMessage: string, channelId: string, chatId: string | undefined | null, userName: string | undefined | null, userEmail: string | undefined | null, userInstruction: string | undefined | null, imageBrief: string | undefined | null, onEvent: (err: null | Error, event: NapiStreamEvent) => void): Promise<void>

export declare function updateChatMetadata(metadata: NapiChatMetadata): void

export declare function validateAuthCredentials(): void
