/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeImage(imagePath: string, model: string, userMessage: string | undefined | null, onEvent: (err: null | Error, event: NapiStreamEvent) => void): Promise<NapiAnalyzeResult>

export declare function appendThreadMessage(threadId: string, role: string, content: string): void

export declare function cacheAvatar(url: string, profileId?: string | undefined | null): Promise<string>

export declare function cancelDownloadOcrModel(modelId: string): void

export declare function cancelGoogleAuth(): void

export declare function cancelRequest(channelId?: string | undefined | null): Promise<void>

export declare function checkSttVersion(): void

export declare function clearActiveProfile(): void

export declare function compressConversation(apiKey: string, imageBrief: string, historyToCompress: string, model: string): Promise<string>

export declare function copyImageFromPathToClipboard(path: string): void

export declare function copyImageToClipboard(imageBase64: string): void

export declare function createThread(title: string, imageHash: string, ocrLang?: string | undefined | null): NapiThreadMetadata

export declare function createThreadJson(title: string, imageHash: string, ocrLang?: string | undefined | null): string

export declare function deleteProfile(profileId: string): void

export declare function deleteThread(threadId: string): void

export declare function detectImageTone(bytes: Buffer): string | null

export declare function downloadOcrModel(modelId: string, url: string, progressCb: (progressJson: string) => void): Promise<string>

export declare function encryptAndSave(profileId: string, provider: string, plaintext: string): void

export declare function findProfileByEmail(email: string): NapiProfile | null

export declare function generateImageBrief(apiKey: string, imagePath: string, model: string): Promise<string>

export declare function generateThreadTitle(apiKey: string, model: string, promptContext: string): Promise<string>

export declare function getActiveProfileId(): string | null

export declare function getApiKey(profileId: string, provider: string): string | null

export declare function getIdentityConfig(): NapiIdentityConfig

export declare function getImagePath(hash: string): string

export declare function getImgbbUrl(threadId: string): string | null

export declare function getLinuxPackageManager(): string

export declare function getMachineInfo(): string

export declare function getModelPath(modelId: string): string

export declare function getProfile(profileId: string): NapiProfile | null

export declare function getRollingSummary(threadId: string): string | null

export declare function getStoreBaseDir(): string

export declare function getSystemTheme(): string

export declare function hasProfiles(): boolean

export declare function listDownloadedModels(): Array<string>

export declare function listProfiles(): Array<NapiProfile>

export declare function listThreads(): Array<NapiThreadMetadata>

export declare function listThreadsJson(): string

export declare function loadThread(threadId: string): NapiThreadData

export declare function loadThreadJson(threadId: string): string

export interface NapiAnalyzeResult {
  threadId: string
  title: string
  assistantMessage: string
  imagePath: string
  imageBrief?: string
}

export interface NapiAuthResult {
  id: string
  name: string
  email: string
  avatar: string
  originalPicture?: string
}

export interface NapiIdentityConfig {
  prompt: string
  soul?: NapiSoul
}

export interface NapiProfile {
  id: string
  name: string
  email: string
  avatar?: string
  originalAvatar?: string
  createdAt: string
  lastUsedAt: string
}

export interface NapiPromptResult {
  threadId: string
  assistantMessage: string
  normalizedUserMessage: string
}

export interface NapiSoul {
  name: string
}

export interface NapiStoredImage {
  hash: string
  path: string
  tone?: string
}

/** Stream event sent via ThreadsafeFunction callback. */
export interface NapiStreamEvent {
  eventType: string
  token?: string
  message?: string
  id?: string
  name?: string
  status?: string
  args?: string
  result?: string
}

export interface NapiThreadData {
  metadata: NapiThreadMetadata
  messages: Array<NapiThreadMessage>
  rollingSummary?: string
  imageBrief?: string
  imgbbUrl?: string
}

export interface NapiThreadMessage {
  role: string
  content: string
  timestamp: string
}

export interface NapiThreadMetadata {
  id: string
  title: string
  imageHash: string
  createdAt: string
  updatedAt: string
  isPinned: boolean
  ocrLang?: string
  imageTone?: string
}

export declare function ocrImage(imagePath: string, isBase64: boolean, modelName: string): Promise<string>

export declare function playUiSound(effect: string): void

export declare function processImagePath(path: string): NapiStoredImage

export declare function profileCount(): number

export declare function promptThread(threadId: string, model: string, userMessage: string, onEvent: (err: null | Error, event: NapiStreamEvent) => void): Promise<NapiPromptResult>

export declare function readClipboardImage(): NapiStoredImage

export declare function readClipboardText(): string

export declare function removeIdentitySoul(): void

export declare function requestQuickAnswer(channelId: string): Promise<void>

export declare function revealInFileManager(path: string): void

export declare function runSidecarVersion(command: string): Promise<string>

export declare function saveApiKey(profileId: string, provider: string, key: string): string

export declare function saveImageTone(threadId: string, tone: string): void

export declare function saveImgbbUrl(threadId: string, url: string): void

export declare function saveRollingSummary(threadId: string, summary: string): void

export declare function setActiveProfile(profileId: string): void

export declare function setIdentityPrompt(prompt: string): void

export declare function setIdentitySoul(name: string, markdown: string): void

export declare function startGoogleAuth(): Promise<NapiAuthResult>

export declare function storeFileFromPath(path: string): NapiStoredImage

export declare function storeImageFromPath(path: string): NapiStoredImage

export declare function streamThread(apiKey: string, model: string, isInitialTurn: boolean, imagePath: string | undefined | null, imageDescription: string | undefined | null, userFirstMsg: string | undefined | null, historyLog: string | undefined | null, rollingSummary: string | undefined | null, userMessage: string, channelId: string, threadId: string | undefined | null, userName: string | undefined | null, userEmail: string | undefined | null, imageBrief: string | undefined | null, onEvent: (err: null | Error, event: NapiStreamEvent) => void): Promise<void>

export declare function updateThreadMetadata(metadata: NapiThreadMetadata): void

export declare function updateThreadMetadataJson(metadataJson: string): void

export declare function uploadImageToImgbb(imagePath: string, apiKey: string): Promise<string>

export declare function validateAuthCredentials(): void
